sudo: required
dist: trusty

language: node_js
node_js: "4"

cache:
  directories:
    - node_modules

matrix:
  include:
    - node_js: "5"
    - node_js: "6"

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
